version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: Social-Big
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://postgres:12345@db:5432/Social-Big"
      PORT: 3001
      JWT_SECRET: "TGaJIpgzUVIYAWQPe8HEWCcxVd9RgcTGl4Bdok"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    command: >
      sh -c "
      npx prisma migrate deploy &&
      npm run dev
      "

volumes:
  db_data:
